# Generated by Django 3.2.4 on 2021-06-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0002_parser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='default',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='features',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='pos_take',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='regex_take',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='regex_valid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='site',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='xpath',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
