# Generated by Django 3.2.4 on 2021-07-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0003_auto_20210613_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='len_valid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
